try {
  someFunc();
} catch {
  // 아무것도 하지 않는다
}
